# Generated by Django 2.0.1 on 2018-03-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_logapisearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logapisearch',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
