# Generated by Django 2.0.1 on 2018-02-02 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import passhint.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('regex', models.CharField(max_length=200)),
                ('regex_result', models.BooleanField()),
                ('desc_ko', models.CharField(max_length=200)),
                ('desc_en', models.CharField(max_length=200)),
                ('desc_short', models.CharField(max_length=200)),
                ('error_ko', models.CharField(max_length=200)),
                ('error_en', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('len_min', models.SmallIntegerField(blank=True, null=True)),
                ('len_max', models.SmallIntegerField(blank=True, null=True)),
                ('exc_special', models.NullBooleanField(default=None)),
                ('exc_space', models.NullBooleanField(default=None)),
                ('exc_same', models.NullBooleanField(default=None)),
                ('exc_series', models.NullBooleanField(default=None)),
                ('exc_id', models.NullBooleanField(default=None)),
                ('exc_common', models.NullBooleanField(default=None)),
                ('inc_special', models.NullBooleanField(default=None)),
                ('inc_lower', models.NullBooleanField(default=None)),
                ('inc_upper', models.NullBooleanField(default=None)),
                ('inc_number', models.NullBooleanField(default=None)),
                ('inc_letter', models.NullBooleanField(default=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tag', models.CharField(max_length=200)),
                ('hit', models.BigIntegerField(default=0)),
                ('main_url', models.CharField(max_length=100, validators=[passhint.models.url_validator])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
