# Generated by Django 2.0.1 on 2018-02-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='rule_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passhint.RuleSet'),
        ),
    ]
