# Generated by Django 2.0.1 on 2018-02-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0002_site_rule_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='passhint.RuleSet'),
        ),
    ]
