# Generated by Django 2.0.1 on 2018-02-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0003_auto_20180203_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='regex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='regex_result',
            field=models.NullBooleanField(),
        ),
    ]
