# Generated by Django 2.0.1 on 2018-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0004_auto_20180203_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='exc_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='exc_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='exc_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='exc_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='exc_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='exc_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='inc_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='inc_lower',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='inc_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='inc_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='inc_upper',
            field=models.BooleanField(default=False),
        ),
    ]
