# Generated by Django 2.0.1 on 2018-02-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0005_auto_20180203_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='rule_set',
        ),
        migrations.AddField(
            model_name='ruleset',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='passhint.Site'),
            preserve_default=False,
        ),
    ]
