# Generated by Django 2.0.1 on 2018-02-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0006_auto_20180203_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='passhint.Site'),
        ),
    ]
