# Generated by Django 2.0.1 on 2018-02-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0008_site_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
