# Generated by Django 2.0.1 on 2018-02-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0010_auto_20180214_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created_at']},
        ),
    ]
