# Generated by Django 2.0.1 on 2018-02-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0011_auto_20180215_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='status',
        ),
    ]
