# Generated by Django 2.0.1 on 2018-02-15 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import passhint.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passhint', '0012_remove_site_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('rejected', 'rejected')], default='waiting', max_length=10)),
                ('main_url', models.CharField(max_length=100, validators=[passhint.models.url_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
