# Generated by Django 2.0.1 on 2018-02-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0014_reportruleset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportruleset',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('rejected', 'rejected'), ('late', 'late')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportsite',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('rejected', 'rejected'), ('late', 'late')], default='waiting', max_length=10),
        ),
    ]
