# Generated by Django 2.0.1 on 2018-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0016_auto_20180224_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='rule',
            name='label',
            field=models.CharField(default='New rule', max_length=50),
        ),
    ]
