# Generated by Django 2.0.1 on 2018-03-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0017_auto_20180224_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='label',
        ),
        migrations.AddField(
            model_name='rule',
            name='guide_en',
            field=models.CharField(default='gogo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='guide_ko',
            field=models.CharField(default='gogo', max_length=200),
            preserve_default=False,
        ),
    ]
