# Generated by Django 2.0.1 on 2018-03-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passhint', '0018_auto_20180302_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='inc_2_of_letter_num_special',
            field=models.BooleanField(default=False),
        ),
    ]
